title: Nube IO
subtitle: "A fast, simple & powerful blog framework powered by Node.js."
description: "Best in the what we do!"
author: Aidan And Lina
language: en
timezone: UTC
url: https://hexo.io
root: /
permalink: news/:day/:month/:year/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :day-:month-:year-:title.md # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

theme: navy
deploy:
  type: git
  repo: git@github.com:hexojs/hexojs.github.io.git

disqus_shortname: hexojs
google_analytics: UA-4910098-10
fb_admins: 100000247608790
algolia:
  en:
    api_key: f820e8f3fe4b5112cefba4c757798e87
    index_name: hexo
  zh-tw:
    api_key: c83d2ec3440f40aec6d0e695ecec7ef3
    index_name: hexo_zh-tw
  zh-cn:
    api_key: cdea7d4e47d84f6145b77e7f68689f35
    index_name: hexo_zh-cn
twitter: hexojs
github: hexojs/hexo
